# Qwen3 AI Integration Configuration
ai:
  qwen3:
    api-key: ${QWEN3_API_KEY:your-qwen3-api-key-here}
    model: qwen-turbo
    max-tokens: 2048
    temperature: 0.7
    api-url: https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation

# System data collection settings
system:
  data:
    collection-interval: 300000  # 5 minutes in milliseconds
    max-history-size: 1000
    enable-real-time-monitoring: true

# Logging configuration for Qwen3 integration
logging:
  level:
    com.chatbot.service.impl.Qwen3ServiceImpl: DEBUG
    com.chatbot.service.SystemDataProcessor: INFO
    com.chatbot.controller.Qwen3Controller: INFO

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /

# Spring configuration
spring:
  application:
    name: qwen3-ai-integration
  
  # Database configuration (if needed)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  
  h2:
    console:
      enabled: true
      path: /h2-console

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always